# -*- coding: utf-8 -*-
"""ШевляковаПи-311_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xVjQvm6B502E280ogebrJt9RmP4Y5McJ
"""

a=int(input("Сюды нужно написать число "))
if a == 1:
  print("01 - Январь - первый месяц в году")
if a == 2:
  print("02 - Февраль - второй месяц в году")
if a == 3:
  print("03 - Март - третий месяц в году")
if a == 4:
  print("04 - Апрель - четвёртый месяц в году")
if a == 5:
  print("05 - Май - пятый месяц в году")
if a == 6:
  print("06 - Июнь - шестой месяц в году")
if a == 7:
  print("07 - Июль - седьмой месяц в году")
if a == 8:
  print("08 - Август - восьмой месяц в году")
if a == 9:
  print("09 - Сентябрь - девятый месяц в году")
if a == 10:
  print("10 - Октябрь - десятый месяц в году")
if a == 11:
  print("11 - Ноябрь - одиннадцатый месяц в году")
if a == 12:
  print("12 - Декабрь - двенадцатый месяц в году")

a=int(input("любое целое число - "))
if a%2==0:
  print("Твоё число чётное, congrats (вставить эмодзи хлопушки)")
else:
  print("Твоё число нечётное, congrats (вставить эмодзи хлопушки)")

"""щащащаща, я только что придумала одну штуку, сейчас будет дубль два

>redacted

всё забыли, **я познала мироздание**, *буквы не могут быть цифрами*

"""

print("НЕ ПРОЛИСТАЙ! Пройди быстрый тест на то больше ли твоё число сорока (40)!!1!")
a=input("вводи число, только спокойно, ок? не переусердствуй - ")
c=float(a)
if c>100:
  print("серьёзно, больше сотни? а чего не больше тысячи? ну тип CoNgRaTs ТвОё ЧиСлО бОлЬшЕ 40(-ка)")
elif c>1000:
  print("ты правда это сделал? больше тысячи?? CONGRATULATIONS! ТВОЁ ЧИСЛО БОЛЬШЕ СОРОКА - ВОЗЬМИ С ПОЛКИ ПИРОЖОК")
elif c<-1000:
  red='\033[31m'
  reset='\033[0m'
  print(f"{red}Ваш основной IP адрес был сохранён и передан. Ожидайте...{reset}")
  import time
  x=10000
  for i in range (x+1):
    print(x)
    x=x-1
    time.sleep(1)
elif c<0:
  print("ты типо шибко умный или наоборот? ок, отрицательное чило МЕНЬШЕ 40(-ка)")
# и так... теперь можно перейти к основной программе
elif c>40:
  print("Поздравляю! Ваше число больше 40(-ка)")
  print("stonks")
elif c<40:
  print("Поздравляю! Ваше число меньше 40(-ка)")
  print("not stonks, but stonks будь на позитиве")
# ну ещё немного
elif c ==40:
  print("не поздравляю... твоё число равно 40(-ку)")

"""*`люблю Stanly Parable`*"""

a=int(input())
def is_year_leap():
  if a%4==0:
    return True
  else:
    return False
print(is_year_leap())

a=int(input())
def is_prime():
  for i in range (2,10):
    if a==2 or a==3 or a==5 or a==7:
      return True
    elif a%i==0:
      return False
if a>1:
  print(is_prime())
else:
  print("Написано нужно число больше нуля")

import random
o=0
x=round(((-138/2)**1.3).real)
y=round((abs(-69/28**5.1)*4).real)
for i in range(10000):
  a=random.randint(0,10000)
  b=random.randint(0,10000)
  if a*3.6==b or b in  range(x, y):
    o+=1
    print(b,a)
if o==0:
  print("кажись ничего не нашли") # если у вас не nasa-компьютер, можете не проверять с большими значениями

import sys
f=[]
ch=0
otr=0
eptm=0
a=int(input("Слава богу нужно ввести всего пять чисел: "))
if a%2==0:
  ch+=1
if a>-265 and a<1024:
  eptm+=1
if a<0:
  otr+=1
f.append(a)

b=int(input())
if b%2==0:
  ch+=1
if b>-265 and a<1024:
  eptm+=1
if b<0:
  otr+=1
f.append(b)
g=f.count(b)
if g>1:
  sys.exit("Обнажурен недостаток воображния, попробуй придумать неповторяющиеся числа")

c=int(input())
if c%2==0:
  ch+=1
if c>-265 and a<1024:
  eptm+=1
if c<0:
  otr+=1
f.append(c)
g=f.count(c)
if g>1:
  sys.exit("Обнажурен недостаток воображния, попробуй придумать неповторяющиеся числа")

d=int(input())
if d%2==0:
  ch+=1
if d>-265 and a<1024:
  eptm+=1
if d<0:
  otr+=1
f.append(d)
g=f.count(d)
if g>1:
    sys.exit("Обнажурен недостаток воображния, попробуй придумать неповторяющиеся числа")

e=int(input())
if e%2==0:
  ch+=1
if e>-265 and a<1024:
  eptm+=1
if e<0:
  otr+=1
f.append(e)
g=f.count(e)
if g>1:
    sys.exit("Обнажурен недостаток воображния, попробуй придумать неповторяющиеся числа")

print("Кол-во чётных - ",ch)
print("Кол-во отрицательных - ",otr)
print("Входящих в промежуток -256<x<1024 - ",eptm)

a=int(input("a - ")) #2 / 4
b=int(input("b - ")) #0
c=int(input("c - ")) #-2
e=(a**2+b**3)/(c+3)/4
e=round(e)
if e%2==0:
  print("✓")
else:
  print("✗")